# Generated by Django 6.0.3 on 2026-03-18 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_camera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='ip_camera',
            new_name='url_address',
        ),
        migrations.AddField(
            model_name='camera',
            name='ip_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
    ]
