# Generated by Django 6.0.3 on 2026-03-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_ip_camera_camera_url_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='location',
            field=models.CharField(choices=[('san_jose', 'San Jose'), ('cartago', 'Cartago'), ('heredia', 'Heredia'), ('alajuela', 'Alajuela'), ('limon', 'Limon'), ('puntarenas', 'Puntarenas'), ('guanacaste', 'Guanacaste')], default='active', max_length=10),
        ),
    ]
