# Generated by Django 6.0.3 on 2026-03-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_camera_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(choices=[('San José', 'San José'), ('Cartago', 'Cartago'), ('Heredia', 'Heredia'), ('Alajuela', 'Alajuela'), ('Limón', 'Limón'), ('Puntarenas', 'Puntarenas'), ('Guanacaste', 'Guanacaste')], default='San José', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='camera',
            name='location',
            field=models.CharField(choices=[('San José', 'San José'), ('Cartago', 'Cartago'), ('Heredia', 'Heredia'), ('Alajuela', 'Alajuela'), ('Limón', 'Limón'), ('Puntarenas', 'Puntarenas'), ('Guanacaste', 'Guanacaste')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
