# Generated by Django 6.0.3 on 2026-03-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_router_alter_camera_location_alter_camera_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='ip_address',
            field=models.CharField(max_length=80),
        ),
    ]
