# Generated by Django 6.0.3 on 2026-03-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_camera_latitude_camera_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
