# Generated by Django 6.0.3 on 2026-04-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_router_latitude_router_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='location',
            field=models.CharField(choices=[('San José', 'San José'), ('Cartago', 'Cartago'), ('Heredia', 'Heredia'), ('Alajuela', 'Alajuela'), ('Limón', 'Limón'), ('Puntarenas', 'Puntarenas'), ('Guanacaste', 'Guanacaste')], default='San Jose', max_length=20),
        ),
    ]
