# Generated by Django 6.0.3 on 2026-04-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_camera_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
