# Generated by Django 6.0.3 on 2026-05-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_router_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='latency_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='camera',
            name='packet_loss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='camera',
            name='stream_type',
            field=models.CharField(choices=[('MP4', 'MP4'), ('HLS', 'HLS'), ('AWS', 'AWS')], default='MP4', max_length=20),
        ),
        migrations.AddField(
            model_name='camera',
            name='stream_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
