# Generated by Django 6.0.3 on 2026-05-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_camera_latency_ms_camera_packet_loss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='stream_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
