# Generated by Django 6.0.3 on 2026-05-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_camera_stream_url_alter_camera_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Maintenance', 'Maintenance'), ('Inactive', 'Inactive')], default='Maintenance', max_length=15),
        ),
        migrations.AlterField(
            model_name='router',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Maintenance', 'Maintenance'), ('Inactive', 'Inactive')], default='Maintenance', max_length=15),
        ),
    ]
